### ISSUE TITLE
Most are false positives for me

### ISSUE THREAD

**Issue by coffeeandpython** [Suleman-Elahi/WpBrokenCheck#2]
I tried the program on the same site that you have shown in the screenshot (codeitbro.com). I found that almost all of the links in the csv generated are not broken links. Do you think it could be a network issue? Anyway, just wanted to bring it to your notice.

[example.csv](https://github.com/Suleman-Elahi/WpBrokenCheck/files/9775843/example.csv)

**Comment by Suleman-Elahi** [comment]
You are right. I am just making head requests so maybe that's a problem. For example, in this GET request returns 200 but HEAD request is returning 404:

![image](https://user-images.githubusercontent.com/24384996/195585806-5d9d6aba-61fe-4062-b221-29dc15174f21.png)

I'll see what can be done.

**Comment by Suleman-Elahi** [comment]
The `httpx` version can fix this issue.

4cfa4e26388307352b7f59644bb7f6b306202382
